local vendOne = peripheral.wrap("redstone_relay_46")
local vendTwo = peripheral.wrap("redstone_relay_47")
local vendThree = peripheral.wrap("redstone_relay_48")
local vendFour = peripheral.wrap("redstone_relay_49")
local turtle = peripheral.wrap("turtle_13")
turtle.turnLeft()
turtle.turnLeft()
turtle.turnLeft()
turtle.turnLeft()